### ISSUE TITLE
Maken flow

### ISSUE THREAD

**Issue by fredbierman** [harriedegroot/nl.hdg.climate#1]
Beste Harry,

Weet niet of dit de juiste plek is maar ik heb je app temperatuur gedownload maar heb geen idee hoe ik de waardes zichtbaar krijg in bv een flow
Zou je me hiermee kunnen helpen

Bedankt fred

**Comment by harriedegroot** [comment]
Deze app heeft geen flow integratie, daarvoor zul je de afzonderlijke apparaten moeten uitlezen.
En dit is inderdaad niet de meest handige plek voor bovenstaande vraag :), het forum of slack zijn hiervoor betere alternatieven.
