### ISSUE TITLE
Temperatuur Monitor werkt momenteel niet in Homey pro

### ISSUE THREAD

**Issue by KesieP** [harriedegroot/nl.hdg.climate#7]
App installeert wel in Homey Pro (early 2019) en laat ook de temperatuursensoren zien. Maar is niet zichtbaar bij ‘Apparaten’ en in Flows. Doe ik iets niet goed?
Groet
Kees

**Comment by harriedegroot** [comment]
Battery monitor is deprecated. Athom integrated the functionality into the Homey OS.
